palavra = input('Digite uma palavra:  ')
print('O tipo primitivo desse valor é ', type(palavra))
print('Só tem espaços? ', palavra.isspace())
print('É um número? ', palavra.isnumeric())
print('È alfabetico? ', palavra.isalpha())
print('È alfanumerico?', palavra.isalnum)
print('Está em maiúculas?', palavra.isupper())
print('Está em minúsculas?', palavra.islower())
print('Está capitalizada? ', palavra.istitle())