a = int( input (' qual tabuada voce quer ver?'))
print (f' { a * 1}')
print (f' { a * 2}')
print (f' { a * 3}')
print (f' { a * 4}')
print (f' { a * 5}')
print (f' { a * 6}')
print (f' { a * 7}')
print (f' { a * 8}')
print (f' { a * 9}')
print (f' { a * 10}')
