
print('os animes disponiveis são:')
print('')
print('1 - Renegade Immortal ')
print('2 -Battle Through the Heavens')
print('3 -Eclipse of Illusion ')
print('4 -Diário de uma apotecaria ')
print('5 -Atack on Titan')
print('6 -Black clover ')
print('7 -Tokyo revengers')
print('')
information = input('informe o numero do anime que você deseja saber as informaçoês:')
if information == '1':
    print('')
    print('titulo: Renegade Immortal (Fanren Xiu Xian Zhuan)')
    print('autor: Er Gen')
    print('ano: 2023')
    print('genero: Cultivação/Xianxia,')
    print('descricao:História de Wang Lin, um mortal que busca a imortalidade através do cultivo')
elif information == '2':
    print('')
    print('título: Battle Through the Heavens (Doupo Cangqiong)')
    print('autor: Tian Can Tu Dou (Heavenly Silkworm Potato)')
    print('ano: 2009 (lançamento original da webnovel)')
    print('gênero: Cultivação, Fantasia, Aventura, Ação')
    print('descrição: A história segue Xiao Yan, um gênio que perde seu talento e prestígio, mas parte em uma jornada épica para recuperar seu poder e honra com a ajuda de um misterioso espírito de mestre alojado em seu anel.')
elif information == '3':
    print('')
    print('Sem informação no momento.')
    print('')
    print('')
    print('')
    print('')
elif information == '4':
    print('')
    print('título: Diário de uma Apotecária (The Apothecary Diaries / Kusuriya no Hitorigoto)')
    print('autor: Natsu Hyūga (roteiro) e Nekokurage (arte) - para o mangá, baseado na light novel de Natsu Hyūga e ilustrações de Touko Shino.')
    print('ano: 2011 (light novel), 2017 (mangá)')
    print('gênero: Mistério, Histórico, Drama, Comédia')
    print('descrição: Maomao, uma jovem e curiosa farmacêutica, é raptada e vendida para trabalhar no palácio imperial. Usando seu vasto conhecimento de venenos e medicamentos, ela resolve intrigas médicas e crimes, chamando a atenção de um eunuco influente.')
elif information == '5':
    print('')
    print('título: Attack on Titan (Shingeki no Kyojin)')
    print('autor: Hajime Isayama')
    print('ano: 2009')
    print('gênero: Ação, Fantasia Sombria, Drama, Pós-apocalíptico')
    print('descrição: A humanidade vive confinada dentro de cidades cercadas por enormes muralhas para se proteger dos Titãs, criaturas gigantescas que devoram humanos. Eren Yeager e seus amigos se juntam à luta contra essas ameaças após um ataque devastador.')
elif information == '6':
    print('')
    print('título: Black Clover')
    print('autor: Yūki Tabata')
    print('ano: 2015')
    print('gênero: Ação, Fantasia, Comédia, Artes Marciais')
    print('descrição: Num mundo onde magia é tudo, Asta é um jovem raro nascido sem poderes mágicos. Para competir com seu rival Yuno e alcançar seu sonho de se tornar o Rei Mago, ele depende de sua força física única e de um misterioso "grimório do trevo de cinco folhas".')
elif information == '7':
    print('')
    print('título: Tokyo Revengers')
    print('autor: Ken Wakui')
    print('ano: 2017')
    print('gênero: Ação, Drama, Seinen, Viagem no Tempo')
    print('descrição: Takemichi Hanagaki, um desempregado sem perspectivas, descobre que sua ex-namorada foi assassinada por uma gangue. Ele é misteriosamente transportado 12 anos no passado e tem a chance de mudar seu destino e o das pessoas ao seu redor, infiltrando-se na perigosa gangue Tokyo Manji.')
else:
    print('')
    print('Esse numero não está disponível nesse catalago')